### ISSUE TITLE
Farm

### ISSUE THREAD

**Issue by pawlik1306** [pingudiogo/TribalWars#4]
The farm script does not work for me all the time the message that it is impossible to send 5 attacks per second

**Comment by pingudiogo** [comment]
What's the value you have put in the "Refresh time in ms:" field? It must be below 200ms to that it only sends 5 attacks per second.

**Comment by pingudiogo** [comment]
Oh sorry it's not refresh time, it's "Time between attacks in ms:".

**Comment by pawlik1306** [comment]
it was 200 but I changed to 1000 and it was the same

**Comment by pingudiogo** [comment]
Can you send me a print screen of the settings you put in?

**Comment by pawlik1306** [comment]
Ok, maybe you have a discord?

**Comment by pingudiogo** [comment]
Add me there pingudiogo#5428

**Comment by pawlik1306** [comment]
ok I will send later because I'm not at home now
